on: [push, pull_request]
env:
  ci_cd: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version-file: ".python-version"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Install a specific version of uv.
        version: "0.9.5"
        enable-cache: true
    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - name: Activate Virtual Environment
      run: |
        uv sync
        . .venv/bin/activate
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: ~/.cache 
        restore-keys: |
          mkdocs-material-
    - name: Deploy
      run: |
        cd docs
        mkdocs gh-deploy --force
